import os

import eel
from database import add_task
from startup import sync_startup_with_pending

# Calculate the absolute path of the 'dist' folder (generated by React)
base_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
web_dir = os.path.join(base_dir, "dist")


@eel.expose
def schedule_task(contact_name, message_text, target_timestamp):
    """
    Save the message in the database permanently.
    The background service (scheduler.py) will send it at the right time.
    """
    try:
        add_task(contact_name, message_text, target_timestamp)
        sync_startup_with_pending()
        return {"success": True}
    except Exception as e:
        return {"success": False, "error": str(e)}


@eel.expose
def get_pending_tasks_from_db():
    from database import get_pending_tasks

    return get_pending_tasks()


@eel.expose
def get_recent_contacts_from_db():
    from database import get_recent_contacts

    return get_recent_contacts()


@eel.expose
def get_logs():
    try:
        from database import get_db_path

        db_dir = os.path.dirname(get_db_path())
        log_path = os.path.join(db_dir, "logs.txt")
        if not os.path.exists(log_path):
            return ["No logs available at the moment."]

        with open(log_path, "r", encoding="utf-8") as f:
            lines = f.readlines()

        # Returns the last 15 lines
        return [line.strip() for line in lines[-15:]]
    except Exception as e:
        return [f"Error reading logs: {e}"]


@eel.expose
def delete_task_from_db(task_id):
    from database import mark_task_done

    try:
        mark_task_done(task_id, success=True)
        sync_startup_with_pending()
        return {"success": True}
    except Exception as e:
        return {"success": False, "error": str(e)}


if __name__ == "__main__":
    import multiprocessing

    multiprocessing.freeze_support()

    print("Starting AutoSender UI...")

    # Initialize the UI interface
    if not os.path.exists(os.path.join(web_dir, "index.html")):
        print(
            f"Error: index.html not found in {web_dir}. Check if the frontend build is present."
        )

    eel.init(web_dir)

    # Sync startup registration based on whether pending tasks exist
    sync_startup_with_pending()

    try:
        # Try to open with Microsoft Edge (default on Windows)
        eel.start("index.html", size=(500, 680), port=0, mode="edge")
    except OSError:
        print("Edge/Chrome not found in App mode. Opening in default system browser...")
        eel.start("index.html", size=(500, 680), port=0, mode="default")
    except Exception as e:
        print("Generic error while starting Eel app:", e)

